/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * North Landing Disc Return
 * OpenAPI spec version: 0.1.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { customInstance } from './client';
import type { ErrorType } from './client';
export interface AddPhoneRequest {
  number: string;
}

export interface BodyUploadDiscPhoto {
  file: Blob;
}

export type DiscCreateOwnerName = string | null;

export type DiscCreatePhoneNumber = string | null;

export interface DiscCreate {
  manufacturer: string;
  name: string;
  color: string;
  input_date: string;
  owner_name?: DiscCreateOwnerName;
  phone_number?: DiscCreatePhoneNumber;
  is_clear?: boolean;
  is_found?: boolean;
}

export type DiscOutOwnerName = string | null;

export type DiscOutPhoneNumber = string | null;

export interface DiscOut {
  id: string;
  manufacturer: string;
  name: string;
  color: string;
  owner_name: DiscOutOwnerName;
  phone_number: DiscOutPhoneNumber;
  is_clear: boolean;
  input_date: string;
  is_found: boolean;
  is_returned: boolean;
  final_notice_sent: boolean;
  photos?: DiscPhotoOut[];
  created_at: string;
  updated_at: string;
}

export interface DiscPage {
  items: DiscOut[];
  page: number;
  page_size: number;
  total: number;
}

export interface DiscPhotoOut {
  id: string;
  photo_path: string;
  sort_order: number;
}

export type DiscUpdateManufacturer = string | null;

export type DiscUpdateName = string | null;

export type DiscUpdateColor = string | null;

export type DiscUpdateOwnerName = string | null;

export type DiscUpdatePhoneNumber = string | null;

export type DiscUpdateIsClear = boolean | null;

export type DiscUpdateIsFound = boolean | null;

export type DiscUpdateIsReturned = boolean | null;

export interface DiscUpdate {
  manufacturer?: DiscUpdateManufacturer;
  name?: DiscUpdateName;
  color?: DiscUpdateColor;
  owner_name?: DiscUpdateOwnerName;
  phone_number?: DiscUpdatePhoneNumber;
  is_clear?: DiscUpdateIsClear;
  is_found?: DiscUpdateIsFound;
  is_returned?: DiscUpdateIsReturned;
}

export interface HTTPValidationError {
  detail?: ValidationError[];
}

export interface NotifyResult {
  sms_jobs_enqueued: number;
  discs_notified: number;
}

export type PhoneNumberOutVerifiedAt = string | null;

export interface PhoneNumberOut {
  id: string;
  number: string;
  verified: boolean;
  verified_at: PhoneNumberOutVerifiedAt;
}

export interface PhoneSuggestion {
  number: string;
  label: string;
}

export type PickupEventCreateNotes = string | null;

export interface PickupEventCreate {
  start_at: string;
  end_at: string;
  notes?: PickupEventCreateNotes;
}

export type PickupEventOutNotes = string | null;

export type PickupEventOutNotificationsSentAt = string | null;

export interface PickupEventOut {
  id: string;
  start_at: string;
  end_at: string;
  notes: PickupEventOutNotes;
  notifications_sent_at: PickupEventOutNotificationsSentAt;
  sequence: number;
  created_at: string;
}

export type PickupEventUpdateStartAt = string | null;

export type PickupEventUpdateEndAt = string | null;

export type PickupEventUpdateNotes = string | null;

export interface PickupEventUpdate {
  start_at?: PickupEventUpdateStartAt;
  end_at?: PickupEventUpdateEndAt;
  notes?: PickupEventUpdateNotes;
}

export type UpdateUserRequestName = string | null;

export type UpdateUserRequestIsAdmin = boolean | null;

export interface UpdateUserRequest {
  name?: UpdateUserRequestName;
  is_admin?: UpdateUserRequestIsAdmin;
}

export interface UserOut {
  id: string;
  name: string;
  email: string;
  is_admin: boolean;
  phone_numbers?: PhoneNumberOut[];
  created_at: string;
}

export type ValidationErrorLocItem = string | number;

export type ValidationErrorCtx = { [key: string]: unknown };

export interface ValidationError {
  loc: ValidationErrorLocItem[];
  msg: string;
  type: string;
  input?: unknown;
  ctx?: ValidationErrorCtx;
}

export interface VerifyPhoneRequest {
  number: string;
  code: string;
}

export type WishlistDiscCreateManufacturer = string | null;

export type WishlistDiscCreateName = string | null;

export type WishlistDiscCreateColor = string | null;

export type WishlistDiscCreateOwnerName = string | null;

export interface WishlistDiscCreate {
  manufacturer?: WishlistDiscCreateManufacturer;
  name?: WishlistDiscCreateName;
  color?: WishlistDiscCreateColor;
  phone_number: string;
  owner_name?: WishlistDiscCreateOwnerName;
}

export type ListDiscsParams = {
page?: number;
page_size?: number;
is_found?: boolean | null;
is_returned?: boolean | null;
owner_name?: string | null;
};

export type GetSuggestionsParams = {
field: GetSuggestionsField;
};

export type GetSuggestionsField = typeof GetSuggestionsField[keyof typeof GetSuggestionsField];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const GetSuggestionsField = {
  manufacturer: 'manufacturer',
  name: 'name',
  color: 'color',
  owner_name: 'owner_name',
} as const;

export type GetPhoneSuggestionsParams = {
/**
 * @minLength 1
 */
owner_name: string;
};

/**
 * @summary Login Google
 */
export const googleLogin = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/auth/google`, method: 'GET', signal
    },
      );
    }
  



export const getGoogleLoginQueryKey = () => {
    return [
    `/auth/google`
    ] as const;
    }

    
export const getGoogleLoginQueryOptions = <TData = Awaited<ReturnType<typeof googleLogin>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleLoginQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleLogin>>> = ({ signal }) => googleLogin(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GoogleLoginQueryResult = NonNullable<Awaited<ReturnType<typeof googleLogin>>>
export type GoogleLoginQueryError = ErrorType<unknown>


export function useGoogleLogin<TData = Awaited<ReturnType<typeof googleLogin>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleLogin>>,
          TError,
          Awaited<ReturnType<typeof googleLogin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleLogin<TData = Awaited<ReturnType<typeof googleLogin>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleLogin>>,
          TError,
          Awaited<ReturnType<typeof googleLogin>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleLogin<TData = Awaited<ReturnType<typeof googleLogin>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Login Google
 */

export function useGoogleLogin<TData = Awaited<ReturnType<typeof googleLogin>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleLogin>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGoogleLoginQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Auth Google Callback
 */
export const googleCallback = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/auth/google/callback`, method: 'GET', signal
    },
      );
    }
  



export const getGoogleCallbackQueryKey = () => {
    return [
    `/auth/google/callback`
    ] as const;
    }

    
export const getGoogleCallbackQueryOptions = <TData = Awaited<ReturnType<typeof googleCallback>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallback>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGoogleCallbackQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof googleCallback>>> = ({ signal }) => googleCallback(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof googleCallback>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GoogleCallbackQueryResult = NonNullable<Awaited<ReturnType<typeof googleCallback>>>
export type GoogleCallbackQueryError = ErrorType<unknown>


export function useGoogleCallback<TData = Awaited<ReturnType<typeof googleCallback>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallback>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleCallback>>,
          TError,
          Awaited<ReturnType<typeof googleCallback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleCallback<TData = Awaited<ReturnType<typeof googleCallback>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallback>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof googleCallback>>,
          TError,
          Awaited<ReturnType<typeof googleCallback>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGoogleCallback<TData = Awaited<ReturnType<typeof googleCallback>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallback>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Auth Google Callback
 */

export function useGoogleCallback<TData = Awaited<ReturnType<typeof googleCallback>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof googleCallback>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGoogleCallbackQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Logout
 */
export const logout = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<unknown>(
      {url: `/auth/logout`, method: 'POST', signal
    },
      );
    }
  


export const getLogoutMutationOptions = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext> => {

const mutationKey = ['logout'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof logout>>, void> = () => {
          

          return  logout()
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type LogoutMutationResult = NonNullable<Awaited<ReturnType<typeof logout>>>
    
    export type LogoutMutationError = ErrorType<unknown>

    /**
 * @summary Logout
 */
export const useLogout = <TError = ErrorType<unknown>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof logout>>, TError,void, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof logout>>,
        TError,
        void,
        TContext
      > => {

      const mutationOptions = getLogoutMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary List Discs
 */
export const listDiscs = (
    params?: ListDiscsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscPage>(
      {url: `/discs`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getListDiscsQueryKey = (params?: ListDiscsParams,) => {
    return [
    `/discs`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getListDiscsQueryOptions = <TData = Awaited<ReturnType<typeof listDiscs>>, TError = ErrorType<HTTPValidationError>>(params?: ListDiscsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDiscs>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getListDiscsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof listDiscs>>> = ({ signal }) => listDiscs(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof listDiscs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type ListDiscsQueryResult = NonNullable<Awaited<ReturnType<typeof listDiscs>>>
export type ListDiscsQueryError = ErrorType<HTTPValidationError>


export function useListDiscs<TData = Awaited<ReturnType<typeof listDiscs>>, TError = ErrorType<HTTPValidationError>>(
 params: undefined |  ListDiscsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDiscs>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDiscs>>,
          TError,
          Awaited<ReturnType<typeof listDiscs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDiscs<TData = Awaited<ReturnType<typeof listDiscs>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListDiscsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDiscs>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof listDiscs>>,
          TError,
          Awaited<ReturnType<typeof listDiscs>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useListDiscs<TData = Awaited<ReturnType<typeof listDiscs>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListDiscsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDiscs>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Discs
 */

export function useListDiscs<TData = Awaited<ReturnType<typeof listDiscs>>, TError = ErrorType<HTTPValidationError>>(
 params?: ListDiscsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof listDiscs>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getListDiscsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Disc
 */
export const createDisc = (
    discCreate: DiscCreate,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscOut>(
      {url: `/discs`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: discCreate, signal
    },
      );
    }
  


export const getCreateDiscMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDisc>>, TError,{data: DiscCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof createDisc>>, TError,{data: DiscCreate}, TContext> => {

const mutationKey = ['createDisc'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof createDisc>>, {data: DiscCreate}> = (props) => {
          const {data} = props ?? {};

          return  createDisc(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type CreateDiscMutationResult = NonNullable<Awaited<ReturnType<typeof createDisc>>>
    export type CreateDiscMutationBody = DiscCreate
    export type CreateDiscMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Disc
 */
export const useCreateDisc = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof createDisc>>, TError,{data: DiscCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof createDisc>>,
        TError,
        {data: DiscCreate},
        TContext
      > => {

      const mutationOptions = getCreateDiscMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Update Disc
 */
export const updateDisc = (
    discId: string,
    discUpdate: DiscUpdate,
 ) => {
      
      
      return customInstance<DiscOut>(
      {url: `/discs/${discId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: discUpdate
    },
      );
    }
  


export const getUpdateDiscMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDisc>>, TError,{discId: string;data: DiscUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof updateDisc>>, TError,{discId: string;data: DiscUpdate}, TContext> => {

const mutationKey = ['updateDisc'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof updateDisc>>, {discId: string;data: DiscUpdate}> = (props) => {
          const {discId,data} = props ?? {};

          return  updateDisc(discId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UpdateDiscMutationResult = NonNullable<Awaited<ReturnType<typeof updateDisc>>>
    export type UpdateDiscMutationBody = DiscUpdate
    export type UpdateDiscMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Disc
 */
export const useUpdateDisc = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof updateDisc>>, TError,{discId: string;data: DiscUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof updateDisc>>,
        TError,
        {discId: string;data: DiscUpdate},
        TContext
      > => {

      const mutationOptions = getUpdateDiscMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete Disc
 */
export const deleteDisc = (
    discId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/discs/${discId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteDiscMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDisc>>, TError,{discId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteDisc>>, TError,{discId: string}, TContext> => {

const mutationKey = ['deleteDisc'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDisc>>, {discId: string}> = (props) => {
          const {discId} = props ?? {};

          return  deleteDisc(discId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDiscMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDisc>>>
    
    export type DeleteDiscMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Disc
 */
export const useDeleteDisc = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDisc>>, TError,{discId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDisc>>,
        TError,
        {discId: string},
        TContext
      > => {

      const mutationOptions = getDeleteDiscMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Upload Disc Photo
 */
export const uploadDiscPhoto = (
    discId: string,
    bodyUploadDiscPhoto: BodyUploadDiscPhoto,
 signal?: AbortSignal
) => {
      
      const formData = new FormData();
formData.append(`file`, bodyUploadDiscPhoto.file)

      return customInstance<DiscPhotoOut>(
      {url: `/discs/${discId}/photos`, method: 'POST',
      headers: {'Content-Type': 'multipart/form-data', },
       data: formData, signal
    },
      );
    }
  


export const getUploadDiscPhotoMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadDiscPhoto>>, TError,{discId: string;data: BodyUploadDiscPhoto}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof uploadDiscPhoto>>, TError,{discId: string;data: BodyUploadDiscPhoto}, TContext> => {

const mutationKey = ['uploadDiscPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof uploadDiscPhoto>>, {discId: string;data: BodyUploadDiscPhoto}> = (props) => {
          const {discId,data} = props ?? {};

          return  uploadDiscPhoto(discId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UploadDiscPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof uploadDiscPhoto>>>
    export type UploadDiscPhotoMutationBody = BodyUploadDiscPhoto
    export type UploadDiscPhotoMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Upload Disc Photo
 */
export const useUploadDiscPhoto = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof uploadDiscPhoto>>, TError,{discId: string;data: BodyUploadDiscPhoto}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof uploadDiscPhoto>>,
        TError,
        {discId: string;data: BodyUploadDiscPhoto},
        TContext
      > => {

      const mutationOptions = getUploadDiscPhotoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Delete Disc Photo
 */
export const deleteDiscPhoto = (
    discId: string,
    photoId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/discs/${discId}/photos/${photoId}`, method: 'DELETE'
    },
      );
    }
  


export const getDeleteDiscPhotoMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDiscPhoto>>, TError,{discId: string;photoId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof deleteDiscPhoto>>, TError,{discId: string;photoId: string}, TContext> => {

const mutationKey = ['deleteDiscPhoto'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof deleteDiscPhoto>>, {discId: string;photoId: string}> = (props) => {
          const {discId,photoId} = props ?? {};

          return  deleteDiscPhoto(discId,photoId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type DeleteDiscPhotoMutationResult = NonNullable<Awaited<ReturnType<typeof deleteDiscPhoto>>>
    
    export type DeleteDiscPhotoMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Delete Disc Photo
 */
export const useDeleteDiscPhoto = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof deleteDiscPhoto>>, TError,{discId: string;photoId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof deleteDiscPhoto>>,
        TError,
        {discId: string;photoId: string},
        TContext
      > => {

      const mutationOptions = getDeleteDiscPhotoMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get Me
 */
export const getMe = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserOut>(
      {url: `/users/me`, method: 'GET', signal
    },
      );
    }
  



export const getGetMeQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }

    
export const getGetMeQueryOptions = <TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMeQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMe>>> = ({ signal }) => getMe(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMeQueryResult = NonNullable<Awaited<ReturnType<typeof getMe>>>
export type GetMeQueryError = ErrorType<unknown>


export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMe>>,
          TError,
          Awaited<ReturnType<typeof getMe>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Me
 */

export function useGetMe<TData = Awaited<ReturnType<typeof getMe>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMe>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMeQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add Phone
 */
export const addPhone = (
    addPhoneRequest: AddPhoneRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PhoneNumberOut>(
      {url: `/users/me/phones`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: addPhoneRequest, signal
    },
      );
    }
  


export const getAddPhoneMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPhone>>, TError,{data: AddPhoneRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addPhone>>, TError,{data: AddPhoneRequest}, TContext> => {

const mutationKey = ['addPhone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addPhone>>, {data: AddPhoneRequest}> = (props) => {
          const {data} = props ?? {};

          return  addPhone(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddPhoneMutationResult = NonNullable<Awaited<ReturnType<typeof addPhone>>>
    export type AddPhoneMutationBody = AddPhoneRequest
    export type AddPhoneMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Phone
 */
export const useAddPhone = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addPhone>>, TError,{data: AddPhoneRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addPhone>>,
        TError,
        {data: AddPhoneRequest},
        TContext
      > => {

      const mutationOptions = getAddPhoneMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Verify Phone
 */
export const verifyPhone = (
    verifyPhoneRequest: VerifyPhoneRequest,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PhoneNumberOut>(
      {url: `/users/me/phones/verify`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: verifyPhoneRequest, signal
    },
      );
    }
  


export const getVerifyPhoneMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyPhone>>, TError,{data: VerifyPhoneRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof verifyPhone>>, TError,{data: VerifyPhoneRequest}, TContext> => {

const mutationKey = ['verifyPhone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof verifyPhone>>, {data: VerifyPhoneRequest}> = (props) => {
          const {data} = props ?? {};

          return  verifyPhone(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type VerifyPhoneMutationResult = NonNullable<Awaited<ReturnType<typeof verifyPhone>>>
    export type VerifyPhoneMutationBody = VerifyPhoneRequest
    export type VerifyPhoneMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Verify Phone
 */
export const useVerifyPhone = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof verifyPhone>>, TError,{data: VerifyPhoneRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof verifyPhone>>,
        TError,
        {data: VerifyPhoneRequest},
        TContext
      > => {

      const mutationOptions = getVerifyPhoneMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Remove Phone
 */
export const removePhone = (
    number: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/users/me/phones/${number}`, method: 'DELETE'
    },
      );
    }
  


export const getRemovePhoneMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removePhone>>, TError,{number: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removePhone>>, TError,{number: string}, TContext> => {

const mutationKey = ['removePhone'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removePhone>>, {number: string}> = (props) => {
          const {number} = props ?? {};

          return  removePhone(number,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemovePhoneMutationResult = NonNullable<Awaited<ReturnType<typeof removePhone>>>
    
    export type RemovePhoneMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Remove Phone
 */
export const useRemovePhone = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removePhone>>, TError,{number: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removePhone>>,
        TError,
        {number: string},
        TContext
      > => {

      const mutationOptions = getRemovePhoneMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get My Wishlist
 */
export const getMyWishlist = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscOut[]>(
      {url: `/users/me/wishlist`, method: 'GET', signal
    },
      );
    }
  



export const getGetMyWishlistQueryKey = () => {
    return [
    `/users/me/wishlist`
    ] as const;
    }

    
export const getGetMyWishlistQueryOptions = <TData = Awaited<ReturnType<typeof getMyWishlist>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWishlist>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetMyWishlistQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyWishlist>>> = ({ signal }) => getMyWishlist(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getMyWishlist>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetMyWishlistQueryResult = NonNullable<Awaited<ReturnType<typeof getMyWishlist>>>
export type GetMyWishlistQueryError = ErrorType<unknown>


export function useGetMyWishlist<TData = Awaited<ReturnType<typeof getMyWishlist>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWishlist>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyWishlist>>,
          TError,
          Awaited<ReturnType<typeof getMyWishlist>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyWishlist<TData = Awaited<ReturnType<typeof getMyWishlist>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWishlist>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getMyWishlist>>,
          TError,
          Awaited<ReturnType<typeof getMyWishlist>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetMyWishlist<TData = Awaited<ReturnType<typeof getMyWishlist>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWishlist>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get My Wishlist
 */

export function useGetMyWishlist<TData = Awaited<ReturnType<typeof getMyWishlist>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyWishlist>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetMyWishlistQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const getMyDiscs = (signal?: AbortSignal) => {
  return customInstance<DiscOut[]>({ url: `/users/me/discs`, method: 'GET', signal });
}

export const getGetMyDiscsQueryKey = () => [`/users/me/discs`] as const;

export const getGetMyDiscsQueryOptions = <TData = Awaited<ReturnType<typeof getMyDiscs>>, TError = ErrorType<unknown>>(options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyDiscs>>, TError, TData>> }) => {
  const { query: queryOptions } = options ?? {};
  const queryKey = queryOptions?.queryKey ?? getGetMyDiscsQueryKey();
  const queryFn: QueryFunction<Awaited<ReturnType<typeof getMyDiscs>>> = ({ signal }) => getMyDiscs(signal);
  return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<Awaited<ReturnType<typeof getMyDiscs>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> };
}

export function useGetMyDiscs<TData = Awaited<ReturnType<typeof getMyDiscs>>, TError = ErrorType<unknown>>(
  options?: { query?: Partial<UseQueryOptions<Awaited<ReturnType<typeof getMyDiscs>>, TError, TData>> },
  queryClient?: QueryClient,
): UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {
  const queryOptions = getGetMyDiscsQueryOptions(options);
  const query = useQuery(queryOptions, queryClient) as UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };
  query.queryKey = queryOptions.queryKey;
  return query;
}


/**
 * @summary Add Wishlist Disc
 */
export const addWishlistDisc = (
    wishlistDiscCreate: WishlistDiscCreate,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscOut>(
      {url: `/users/me/wishlist`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wishlistDiscCreate, signal
    },
      );
    }
  


export const getAddWishlistDiscMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addWishlistDisc>>, TError,{data: WishlistDiscCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof addWishlistDisc>>, TError,{data: WishlistDiscCreate}, TContext> => {

const mutationKey = ['addWishlistDisc'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof addWishlistDisc>>, {data: WishlistDiscCreate}> = (props) => {
          const {data} = props ?? {};

          return  addWishlistDisc(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AddWishlistDiscMutationResult = NonNullable<Awaited<ReturnType<typeof addWishlistDisc>>>
    export type AddWishlistDiscMutationBody = WishlistDiscCreate
    export type AddWishlistDiscMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add Wishlist Disc
 */
export const useAddWishlistDisc = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof addWishlistDisc>>, TError,{data: WishlistDiscCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof addWishlistDisc>>,
        TError,
        {data: WishlistDiscCreate},
        TContext
      > => {

      const mutationOptions = getAddWishlistDiscMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Remove Wishlist Disc
 */
export const removeWishlistDisc = (
    discId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/users/me/wishlist/${discId}`, method: 'DELETE'
    },
      );
    }
  


export const getRemoveWishlistDiscMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeWishlistDisc>>, TError,{discId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof removeWishlistDisc>>, TError,{discId: string}, TContext> => {

const mutationKey = ['removeWishlistDisc'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof removeWishlistDisc>>, {discId: string}> = (props) => {
          const {discId} = props ?? {};

          return  removeWishlistDisc(discId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type RemoveWishlistDiscMutationResult = NonNullable<Awaited<ReturnType<typeof removeWishlistDisc>>>
    
    export type RemoveWishlistDiscMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Remove Wishlist Disc
 */
export const useRemoveWishlistDisc = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof removeWishlistDisc>>, TError,{discId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof removeWishlistDisc>>,
        TError,
        {discId: string},
        TContext
      > => {

      const mutationOptions = getRemoveWishlistDiscMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary List Users
 */
export const adminListUsers = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<UserOut[]>(
      {url: `/admin/users`, method: 'GET', signal
    },
      );
    }
  



export const getAdminListUsersQueryKey = () => {
    return [
    `/admin/users`
    ] as const;
    }

    
export const getAdminListUsersQueryOptions = <TData = Awaited<ReturnType<typeof adminListUsers>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListUsersQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListUsers>>> = ({ signal }) => adminListUsers(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListUsersQueryResult = NonNullable<Awaited<ReturnType<typeof adminListUsers>>>
export type AdminListUsersQueryError = ErrorType<unknown>


export function useAdminListUsers<TData = Awaited<ReturnType<typeof adminListUsers>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListUsers>>,
          TError,
          Awaited<ReturnType<typeof adminListUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListUsers<TData = Awaited<ReturnType<typeof adminListUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListUsers>>,
          TError,
          Awaited<ReturnType<typeof adminListUsers>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListUsers<TData = Awaited<ReturnType<typeof adminListUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Users
 */

export function useAdminListUsers<TData = Awaited<ReturnType<typeof adminListUsers>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListUsers>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListUsersQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Update User
 */
export const adminUpdateUser = (
    userId: string,
    updateUserRequest: UpdateUserRequest,
 ) => {
      
      
      return customInstance<UserOut>(
      {url: `/admin/users/${userId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: updateUserRequest
    },
      );
    }
  


export const getAdminUpdateUserMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateUser>>, TError,{userId: string;data: UpdateUserRequest}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdateUser>>, TError,{userId: string;data: UpdateUserRequest}, TContext> => {

const mutationKey = ['adminUpdateUser'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdateUser>>, {userId: string;data: UpdateUserRequest}> = (props) => {
          const {userId,data} = props ?? {};

          return  adminUpdateUser(userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdateUserMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdateUser>>>
    export type AdminUpdateUserMutationBody = UpdateUserRequest
    export type AdminUpdateUserMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update User
 */
export const useAdminUpdateUser = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdateUser>>, TError,{userId: string;data: UpdateUserRequest}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdateUser>>,
        TError,
        {userId: string;data: UpdateUserRequest},
        TContext
      > => {

      const mutationOptions = getAdminUpdateUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get User Wishlist
 */
export const adminGetUserWishlist = (
    userId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscOut[]>(
      {url: `/admin/users/${userId}/wishlist`, method: 'GET', signal
    },
      );
    }
  



export const getAdminGetUserWishlistQueryKey = (userId?: string,) => {
    return [
    `/admin/users/${userId}/wishlist`
    ] as const;
    }

    
export const getAdminGetUserWishlistQueryOptions = <TData = Awaited<ReturnType<typeof adminGetUserWishlist>>, TError = ErrorType<HTTPValidationError>>(userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetUserWishlist>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminGetUserWishlistQueryKey(userId);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminGetUserWishlist>>> = ({ signal }) => adminGetUserWishlist(userId, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(userId), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminGetUserWishlist>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminGetUserWishlistQueryResult = NonNullable<Awaited<ReturnType<typeof adminGetUserWishlist>>>
export type AdminGetUserWishlistQueryError = ErrorType<HTTPValidationError>


export function useAdminGetUserWishlist<TData = Awaited<ReturnType<typeof adminGetUserWishlist>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetUserWishlist>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetUserWishlist>>,
          TError,
          Awaited<ReturnType<typeof adminGetUserWishlist>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetUserWishlist<TData = Awaited<ReturnType<typeof adminGetUserWishlist>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetUserWishlist>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminGetUserWishlist>>,
          TError,
          Awaited<ReturnType<typeof adminGetUserWishlist>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminGetUserWishlist<TData = Awaited<ReturnType<typeof adminGetUserWishlist>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetUserWishlist>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get User Wishlist
 */

export function useAdminGetUserWishlist<TData = Awaited<ReturnType<typeof adminGetUserWishlist>>, TError = ErrorType<HTTPValidationError>>(
 userId: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminGetUserWishlist>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminGetUserWishlistQueryOptions(userId,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Add User Wishlist
 */
export const adminAddUserWishlist = (
    userId: string,
    wishlistDiscCreate: WishlistDiscCreate,
 signal?: AbortSignal
) => {
      
      
      return customInstance<DiscOut>(
      {url: `/admin/users/${userId}/wishlist`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: wishlistDiscCreate, signal
    },
      );
    }
  


export const getAdminAddUserWishlistMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddUserWishlist>>, TError,{userId: string;data: WishlistDiscCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminAddUserWishlist>>, TError,{userId: string;data: WishlistDiscCreate}, TContext> => {

const mutationKey = ['adminAddUserWishlist'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminAddUserWishlist>>, {userId: string;data: WishlistDiscCreate}> = (props) => {
          const {userId,data} = props ?? {};

          return  adminAddUserWishlist(userId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminAddUserWishlistMutationResult = NonNullable<Awaited<ReturnType<typeof adminAddUserWishlist>>>
    export type AdminAddUserWishlistMutationBody = WishlistDiscCreate
    export type AdminAddUserWishlistMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Add User Wishlist
 */
export const useAdminAddUserWishlist = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminAddUserWishlist>>, TError,{userId: string;data: WishlistDiscCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminAddUserWishlist>>,
        TError,
        {userId: string;data: WishlistDiscCreate},
        TContext
      > => {

      const mutationOptions = getAdminAddUserWishlistMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Remove User Wishlist
 */
export const adminRemoveUserWishlist = (
    userId: string,
    discId: string,
 ) => {
      
      
      return customInstance<void>(
      {url: `/admin/users/${userId}/wishlist/${discId}`, method: 'DELETE'
    },
      );
    }
  


export const getAdminRemoveUserWishlistMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRemoveUserWishlist>>, TError,{userId: string;discId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminRemoveUserWishlist>>, TError,{userId: string;discId: string}, TContext> => {

const mutationKey = ['adminRemoveUserWishlist'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminRemoveUserWishlist>>, {userId: string;discId: string}> = (props) => {
          const {userId,discId} = props ?? {};

          return  adminRemoveUserWishlist(userId,discId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminRemoveUserWishlistMutationResult = NonNullable<Awaited<ReturnType<typeof adminRemoveUserWishlist>>>
    
    export type AdminRemoveUserWishlistMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Remove User Wishlist
 */
export const useAdminRemoveUserWishlist = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminRemoveUserWishlist>>, TError,{userId: string;discId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminRemoveUserWishlist>>,
        TError,
        {userId: string;discId: string},
        TContext
      > => {

      const mutationOptions = getAdminRemoveUserWishlistMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary List Pickup Events
 */
export const adminListPickupEvents = (
    
 signal?: AbortSignal
) => {
      
      
      return customInstance<PickupEventOut[]>(
      {url: `/admin/pickup-events`, method: 'GET', signal
    },
      );
    }
  



export const getAdminListPickupEventsQueryKey = () => {
    return [
    `/admin/pickup-events`
    ] as const;
    }

    
export const getAdminListPickupEventsQueryOptions = <TData = Awaited<ReturnType<typeof adminListPickupEvents>>, TError = ErrorType<unknown>>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPickupEvents>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminListPickupEventsQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminListPickupEvents>>> = ({ signal }) => adminListPickupEvents(signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminListPickupEvents>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminListPickupEventsQueryResult = NonNullable<Awaited<ReturnType<typeof adminListPickupEvents>>>
export type AdminListPickupEventsQueryError = ErrorType<unknown>


export function useAdminListPickupEvents<TData = Awaited<ReturnType<typeof adminListPickupEvents>>, TError = ErrorType<unknown>>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPickupEvents>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPickupEvents>>,
          TError,
          Awaited<ReturnType<typeof adminListPickupEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPickupEvents<TData = Awaited<ReturnType<typeof adminListPickupEvents>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPickupEvents>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminListPickupEvents>>,
          TError,
          Awaited<ReturnType<typeof adminListPickupEvents>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminListPickupEvents<TData = Awaited<ReturnType<typeof adminListPickupEvents>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPickupEvents>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary List Pickup Events
 */

export function useAdminListPickupEvents<TData = Awaited<ReturnType<typeof adminListPickupEvents>>, TError = ErrorType<unknown>>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminListPickupEvents>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminListPickupEventsQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Create Pickup Event
 */
export const adminCreatePickupEvent = (
    pickupEventCreate: PickupEventCreate,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PickupEventOut>(
      {url: `/admin/pickup-events`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: pickupEventCreate, signal
    },
      );
    }
  


export const getAdminCreatePickupEventMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreatePickupEvent>>, TError,{data: PickupEventCreate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminCreatePickupEvent>>, TError,{data: PickupEventCreate}, TContext> => {

const mutationKey = ['adminCreatePickupEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCreatePickupEvent>>, {data: PickupEventCreate}> = (props) => {
          const {data} = props ?? {};

          return  adminCreatePickupEvent(data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCreatePickupEventMutationResult = NonNullable<Awaited<ReturnType<typeof adminCreatePickupEvent>>>
    export type AdminCreatePickupEventMutationBody = PickupEventCreate
    export type AdminCreatePickupEventMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Create Pickup Event
 */
export const useAdminCreatePickupEvent = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCreatePickupEvent>>, TError,{data: PickupEventCreate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCreatePickupEvent>>,
        TError,
        {data: PickupEventCreate},
        TContext
      > => {

      const mutationOptions = getAdminCreatePickupEventMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Update Pickup Event
 */
export const adminUpdatePickupEvent = (
    eventId: string,
    pickupEventUpdate: PickupEventUpdate,
 ) => {
      
      
      return customInstance<PickupEventOut>(
      {url: `/admin/pickup-events/${eventId}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: pickupEventUpdate
    },
      );
    }
  


export const getAdminUpdatePickupEventMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePickupEvent>>, TError,{eventId: string;data: PickupEventUpdate}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePickupEvent>>, TError,{eventId: string;data: PickupEventUpdate}, TContext> => {

const mutationKey = ['adminUpdatePickupEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminUpdatePickupEvent>>, {eventId: string;data: PickupEventUpdate}> = (props) => {
          const {eventId,data} = props ?? {};

          return  adminUpdatePickupEvent(eventId,data,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminUpdatePickupEventMutationResult = NonNullable<Awaited<ReturnType<typeof adminUpdatePickupEvent>>>
    export type AdminUpdatePickupEventMutationBody = PickupEventUpdate
    export type AdminUpdatePickupEventMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Update Pickup Event
 */
export const useAdminUpdatePickupEvent = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminUpdatePickupEvent>>, TError,{eventId: string;data: PickupEventUpdate}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminUpdatePickupEvent>>,
        TError,
        {eventId: string;data: PickupEventUpdate},
        TContext
      > => {

      const mutationOptions = getAdminUpdatePickupEventMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Notify Pickup Event
 */
export const adminNotifyPickupEvent = (
    eventId: string,
 signal?: AbortSignal
) => {
      
      
      return customInstance<NotifyResult>(
      {url: `/admin/pickup-events/${eventId}/notify`, method: 'POST', signal
    },
      );
    }
  


export const getAdminNotifyPickupEventMutationOptions = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminNotifyPickupEvent>>, TError,{eventId: string}, TContext>, }
): UseMutationOptions<Awaited<ReturnType<typeof adminNotifyPickupEvent>>, TError,{eventId: string}, TContext> => {

const mutationKey = ['adminNotifyPickupEvent'];
const {mutation: mutationOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminNotifyPickupEvent>>, {eventId: string}> = (props) => {
          const {eventId} = props ?? {};

          return  adminNotifyPickupEvent(eventId,)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminNotifyPickupEventMutationResult = NonNullable<Awaited<ReturnType<typeof adminNotifyPickupEvent>>>
    
    export type AdminNotifyPickupEventMutationError = ErrorType<HTTPValidationError>

    /**
 * @summary Notify Pickup Event
 */
export const useAdminNotifyPickupEvent = <TError = ErrorType<HTTPValidationError>,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminNotifyPickupEvent>>, TError,{eventId: string}, TContext>, }
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminNotifyPickupEvent>>,
        TError,
        {eventId: string},
        TContext
      > => {

      const mutationOptions = getAdminNotifyPickupEventMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
/**
 * @summary Get Suggestions
 */
export const getSuggestions = (
    params: GetSuggestionsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<string[]>(
      {url: `/suggestions`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetSuggestionsQueryKey = (params?: GetSuggestionsParams,) => {
    return [
    `/suggestions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetSuggestionsQueryOptions = <TData = Awaited<ReturnType<typeof getSuggestions>>, TError = ErrorType<HTTPValidationError>>(params: GetSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuggestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetSuggestionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getSuggestions>>> = ({ signal }) => getSuggestions(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getSuggestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetSuggestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getSuggestions>>>
export type GetSuggestionsQueryError = ErrorType<HTTPValidationError>


export function useGetSuggestions<TData = Awaited<ReturnType<typeof getSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetSuggestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuggestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestions<TData = Awaited<ReturnType<typeof getSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuggestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetSuggestions<TData = Awaited<ReturnType<typeof getSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Suggestions
 */

export function useGetSuggestions<TData = Awaited<ReturnType<typeof getSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetSuggestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




/**
 * @summary Get Phone Suggestions
 */
export const getPhoneSuggestions = (
    params: GetPhoneSuggestionsParams,
 signal?: AbortSignal
) => {
      
      
      return customInstance<PhoneSuggestion[]>(
      {url: `/suggestions/phone`, method: 'GET',
        params, signal
    },
      );
    }
  



export const getGetPhoneSuggestionsQueryKey = (params?: GetPhoneSuggestionsParams,) => {
    return [
    `/suggestions/phone`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getGetPhoneSuggestionsQueryOptions = <TData = Awaited<ReturnType<typeof getPhoneSuggestions>>, TError = ErrorType<HTTPValidationError>>(params: GetPhoneSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoneSuggestions>>, TError, TData>>, }
) => {

const {query: queryOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getGetPhoneSuggestionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getPhoneSuggestions>>> = ({ signal }) => getPhoneSuggestions(params, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof getPhoneSuggestions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type GetPhoneSuggestionsQueryResult = NonNullable<Awaited<ReturnType<typeof getPhoneSuggestions>>>
export type GetPhoneSuggestionsQueryError = ErrorType<HTTPValidationError>


export function useGetPhoneSuggestions<TData = Awaited<ReturnType<typeof getPhoneSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetPhoneSuggestionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoneSuggestions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhoneSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getPhoneSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhoneSuggestions<TData = Awaited<ReturnType<typeof getPhoneSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetPhoneSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoneSuggestions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof getPhoneSuggestions>>,
          TError,
          Awaited<ReturnType<typeof getPhoneSuggestions>>
        > , 'initialData'
      >, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useGetPhoneSuggestions<TData = Awaited<ReturnType<typeof getPhoneSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetPhoneSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoneSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
/**
 * @summary Get Phone Suggestions
 */

export function useGetPhoneSuggestions<TData = Awaited<ReturnType<typeof getPhoneSuggestions>>, TError = ErrorType<HTTPValidationError>>(
 params: GetPhoneSuggestionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof getPhoneSuggestions>>, TError, TData>>, }
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getGetPhoneSuggestionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}
