"""add pickup_events, disc_pickup_notifications, sms_jobs tables

Revision ID: 2b4cfe926358
Revises: 32ad847807c3
Create Date: 2026-04-20 14:58:45.890657

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2b4cfe926358'
down_revision: Union[str, Sequence[str], None] = '32ad847807c3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
